name: Unit Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

env:
  GO_VERSION: 1.23.2

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: go test ./... -cover -race -v
