name: Unit Test

on:
  pull_request:
    branches:
      - '*'

env:
  GO_VERSION: 1.19

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test ./... -cover -race -v
